# Generated by Django 2.2.4 on 2019-08-03 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import regsys_api.authsys.models


class Migration(migrations.Migration):

    dependencies = [
        ('authsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=regsys_api.authsys.models.generate_email_token, max_length=32, unique=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
