# Generated by Django 2.2.7 on 2021-01-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alamat',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
    ]
