# Generated by Django 2.2.4 on 2019-08-05 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authsys', '0004_usertokenmanagers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTokenManagers',
        ),
    ]
