# Generated by Django 2.2.6 on 2019-11-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsys', '0005_delete_usertokenmanagers'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpasswordhandler',
            name='browser',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forgotpasswordhandler',
            name='operating_system',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
