# Generated by Django 2.2.6 on 2019-11-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsys', '0006_auto_20191102_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alergic',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_buktiUploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_vege',
            field=models.BooleanField(default=False),
        ),
    ]
