# Generated by Django 2.2.6 on 2019-11-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsys', '0007_auto_20191102_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_line',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nomor_telepon',
            field=models.IntegerField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
