# Generated by Django 2.2.6 on 2019-11-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_auto_20191102_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.IntegerField(choices=[(1, 'info'), (2, 'error'), (3, 'success'), (4, 'warning')]),
        ),
    ]
