# Generated by Django 2.2.7 on 2019-11-15 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('institution', models.CharField(max_length=100)),
                ('alamat_institusi', models.CharField(max_length=500)),
                ('nama_pendamping', models.CharField(max_length=50)),
                ('nomor_telepon_pendamping', models.CharField(max_length=20)),
                ('invitation_token', models.CharField(default='limpness-shanty-olympics-hence', max_length=100)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hackathon Team',
                'verbose_name_plural': 'Hackathon Teams',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('closed_date', models.DateTimeField(null=True)),
                ('team_max_member', models.IntegerField(default=1)),
                ('team_min_member', models.IntegerField(default=1)),
                ('slug_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Competition Track',
                'verbose_name_plural': 'Competition Tracks',
            },
        ),
        migrations.CreateModel(
            name='HackathonTeamsMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='hackathon.HackathonTeams')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'get_latest_by': 'created_at',
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.AddField(
            model_name='hackathonteams',
            name='members',
            field=models.ManyToManyField(related_name='teams', through='hackathon.HackathonTeamsMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hackathonteams',
            name='team_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hackathonteams',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='hackathon.Track'),
        ),
    ]
