# Generated by Django 2.2.4 on 2019-08-22 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=120)),
                ('team_members', models.IntegerField(default=1)),
                ('invitation_link', models.CharField(default='PIpboKXSAm2fvlRoawOdwHSeSB2IvU19', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('team_leader', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HackathonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.HackathonTeam')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HackathonTeamDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_origin', models.CharField(max_length=120)),
                ('team_address', models.CharField(max_length=300)),
                ('team_phonenumber', models.CharField(max_length=30)),
                ('team_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hackathon.HackathonTeam')),
            ],
        ),
    ]
