# Generated by Django 2.2.7 on 2019-12-13 04:14

from django.db import migrations, models
import regsys_api.hackathon.models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathontask',
            name='task_type',
            field=models.CharField(choices=[('file_uploader', 'File Uploader'), (
                'payment_verification', 'Verifikasi Pembayaran'), ('pengumuman', 'Pengumuman')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(
                default=regsys_api.hackathon.models.generate_token, max_length=100, unique=True),
        ),
    ]
