# Generated by Django 2.2.4 on 2019-08-24 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import regsys_api.authsys.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathonteam',
            old_name='team_members',
            new_name='team_member',
        ),
        migrations.RenameField(
            model_name='hackathonuser',
            old_name='team_name',
            new_name='team_id',
        ),
        migrations.RemoveField(
            model_name='hackathonteam',
            name='invitation_link',
        ),
        migrations.AddField(
            model_name='hackathonteam',
            name='team_id',
            field=models.CharField(default=uuid.uuid1, max_length=32),
        ),
        migrations.AddField(
            model_name='hackathonteam',
            name='team_invite_id',
            field=models.CharField(default=regsys_api.authsys.models.generate_email_token, max_length=100),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='team_name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='hackathonuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HackathonTeamDetails',
        ),
    ]
