# Generated by Django 2.2.7 on 2019-11-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='upriver-starship-clerk-rundown', max_length=100),
        ),
    ]
