# Generated by Django 2.2.6 on 2019-11-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_auto_20191102_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='closed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
