# Generated by Django 2.2.4 on 2019-08-24 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_auto_20190824_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteam',
            name='team_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
