# Generated by Django 2.2.7 on 2019-11-15 10:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_auto_20191115_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('stage_name', models.CharField(max_length=50)),
                ('tracks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_stages', to='hackathon.Track')),
            ],
            options={
                'ordering': ['tracks', 'order'],
            },
        ),
        migrations.CreateModel(
            name='HackathonTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField(null=True)),
                ('require_validation', models.BooleanField(default=False)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hackathon.HackathonStage')),
            ],
        ),
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='lushly-suing-outfit-outgrow', max_length=100),
        ),
        migrations.AddField(
            model_name='hackathonteams',
            name='current_stage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='active', to='hackathon.HackathonStage'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TaskResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('status', models.CharField(choices=[('menunggu_verifikasi', 'Menunggu Verifikasi'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak')], max_length=50)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_response', to='hackathon.HackathonTask')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_response', to='hackathon.HackathonTeams')),
            ],
            options={
                'get_latest_by': 'created_at',
                'unique_together': {('task', 'team')},
            },
        ),
    ]
