# Generated by Django 2.2.7 on 2020-02-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_auto_20191213_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathontask',
            name='max_file_upload',
            field=models.IntegerField(default=10),
        ),
    ]
