# Generated by Django 2.2.7 on 2019-11-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_auto_20191115_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='creamed-tidal-tassel-iodize', max_length=100),
        ),
    ]
