# Generated by Django 2.2.4 on 2019-08-24 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_auto_20190824_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathonteam',
            name='team_member',
        ),
    ]
