# Generated by Django 2.2.7 on 2020-02-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_hackathontask_max_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_shown',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='slug_image',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
