# Generated by Django 2.2.6 on 2019-11-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_auto_20191102_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='image',
        ),
    ]
