# Generated by Django 2.2.6 on 2019-11-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_remove_track_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='slug_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
