# Generated by Django 2.2.6 on 2019-11-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_track_slug_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonteams',
            name='alamat_institusi',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackathonteams',
            name='nama_pendamping',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackathonteams',
            name='nomor_telepon_pendamping',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
