# Generated by Django 2.2.7 on 2019-11-15 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_auto_20191115_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteams',
            name='current_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active', to='hackathon.HackathonTask'),
        ),
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='matching-overhear-lifting-sixth', max_length=100),
        ),
    ]
