# Generated by Django 2.2.7 on 2020-03-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_auto_20200219_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_closed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
