# Generated by Django 2.2.4 on 2019-08-25 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_auto_20190824_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hackathonteams',
            options={'verbose_name': 'Hackathon Team', 'verbose_name_plural': 'Hackathon Teams'},
        ),
    ]
