# Generated by Django 2.2.7 on 2020-09-13 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0006_track_is_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('nomor_identitas', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField(default=None)),
                ('vegetarian_bool', models.BooleanField(default=False)),
                ('alergi_makanan', models.CharField(max_length=120)),
                ('id_line', models.CharField(max_length=30)),
                ('nomor_telepon', models.CharField(max_length=13)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_to_team', to='hackathon.HackathonTeams')),
            ],
        ),
    ]
