# Generated by Django 2.2.4 on 2019-08-25 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0006_auto_20190825_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hackathonteamsmember',
            options={'get_latest_by': 'created_at', 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Competition Track', 'verbose_name_plural': 'Competition Tracks'},
        ),
    ]
