# Generated by Django 2.2.7 on 2019-11-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0006_auto_20191103_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='uptight nineteen immerse composer outcast repeal nature', max_length=100),
        ),
    ]
