# Generated by Django 2.2.7 on 2019-11-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0006_auto_20191115_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hackathontask',
            options={'verbose_name': 'Task Lomba', 'verbose_name_plural': 'Task Lomba'},
        ),
        migrations.AlterModelOptions(
            name='hackathonteams',
            options={'verbose_name': 'Tim', 'verbose_name_plural': 'Tim'},
        ),
        migrations.AlterModelOptions(
            name='hackathonteamsmember',
            options={'get_latest_by': 'created_at', 'verbose_name': 'Anggota Tim', 'verbose_name_plural': 'Anggota Tim'},
        ),
        migrations.AlterModelOptions(
            name='taskresponse',
            options={'get_latest_by': 'created_at', 'verbose_name': 'Respon Task Tim', 'verbose_name_plural': 'Respon Task Tim'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Kompetisi', 'verbose_name_plural': 'Kompetisi'},
        ),
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='pamperer-audition-devalue-roping', max_length=100),
        ),
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.TextField(),
        ),
    ]
