# Generated by Django 2.2.7 on 2019-11-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0007_auto_20191115_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='biaya_pendaftaran',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='customs-whole-lilly-riverbed', max_length=100),
        ),
    ]
