# Generated by Django 2.2.7 on 2019-11-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0007_hackathonteams_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='hatchet-craving-hexagon-chatroom', max_length=100),
        ),
    ]
