# Generated by Django 2.2.7 on 2019-11-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0008_auto_20191106_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='hermit-defile-cranial-capital', max_length=100),
        ),
    ]
