# Generated by Django 2.2.7 on 2019-11-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0008_auto_20191115_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='trimming-sinless-shading-primer', max_length=100),
        ),
    ]
