# Generated by Django 2.2.7 on 2019-11-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0009_auto_20191115_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathontask',
            name='task_type',
            field=models.CharField(choices=[('upload file', 'Uploader File'), ('pengumuman', 'Pengumuman')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='splatter-matter-tidbit-consumer', max_length=100),
        ),
    ]
