# Generated by Django 2.2.7 on 2019-11-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0009_auto_20191106_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='argue-outage-silent-fiber', max_length=100),
        ),
    ]
