# Generated by Django 2.2.7 on 2021-01-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0010_auto_20210129_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonteamsmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='hackathonteamsmember',
            name='id_line',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='hackathonteamsmember',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hackathonteamsmember',
            name='nomor_identitas',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hackathonteamsmember',
            name='nomor_telepon',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='hackathonteamsmember',
            name='tanggal_lahir',
            field=models.DateField(default=None, null=True),
        ),
    ]
