# Generated by Django 2.2.7 on 2019-11-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0010_auto_20191115_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresponse',
            name='announcement_desc',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskresponse',
            name='announcement_title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskresponse',
            name='file_path',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='accurate-abruptly-wobble-amusing', max_length=100),
        ),
    ]
