# Generated by Django 2.2.7 on 2019-11-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0011_auto_20191115_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='darkroom-shove-outgrow-vexingly', max_length=100),
        ),
    ]
