# Generated by Django 2.2.7 on 2021-01-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0011_auto_20210129_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteamsmember',
            name='tanggal_lahir',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
