# Generated by Django 2.2.7 on 2021-01-29 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0012_auto_20210129_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathonteamsmember',
            old_name='nama_lengkap',
            new_name='full_name',
        ),
    ]
