# Generated by Django 2.2.7 on 2019-11-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0012_auto_20191115_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='jacket-animator-possum-ability', max_length=100),
        ),
        migrations.AlterField(
            model_name='taskresponse',
            name='announcement_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='taskresponse',
            name='announcement_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
