# Generated by Django 2.2.7 on 2021-01-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0013_auto_20210130_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathonteamsmember',
            old_name='nomor_identitas',
            new_name='nomor_id',
        ),
    ]
