# Generated by Django 2.2.7 on 2019-11-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0013_auto_20191115_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresponse',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='garden-driver-glisten-footrest', max_length=100),
        ),
    ]
