# Generated by Django 2.2.7 on 2019-11-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0014_auto_20191115_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='spoon-saturday-curler-morse', max_length=100),
        ),
    ]
