# Generated by Django 2.2.7 on 2019-11-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0015_auto_20191115_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='footnote-dwelled-payback-sharper', max_length=100),
        ),
        migrations.AlterField(
            model_name='taskresponse',
            name='announcement_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskresponse',
            name='announcement_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taskresponse',
            name='file_path',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
