# Generated by Django 2.2.7 on 2019-11-16 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0017_auto_20191116_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='wrath-douche-kerchief-explicit', max_length=100),
        ),
        migrations.CreateModel(
            name='TaskAndTaskResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_response_link', to='hackathon.HackathonTask')),
                ('task_response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_response_link', to='hackathon.TaskResponse')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_response_link', to='hackathon.HackathonTeams')),
            ],
        ),
    ]
