# Generated by Django 2.2.7 on 2019-11-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0018_auto_20191116_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='gambling-foyer-volumes-borax', max_length=100),
        ),
        migrations.DeleteModel(
            name='TaskAndTaskResponse',
        ),
    ]
