# Generated by Django 2.2.7 on 2019-11-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0019_auto_20191116_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='pyramid-hemlock-folic-spleen', max_length=100),
        ),
        migrations.CreateModel(
            name='TaskAndTaskResponseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_list', to='hackathon.TaskResponse')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_list', to='hackathon.HackathonTask')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_list', to='hackathon.HackathonTeams')),
            ],
        ),
    ]
