# Generated by Django 2.2.7 on 2019-11-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0020_auto_20191116_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='washbowl-jujitsu-stooge-valley', max_length=100),
        ),
        migrations.DeleteModel(
            name='TaskAndTaskResponseList',
        ),
    ]
