# Generated by Django 2.2.7 on 2019-11-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0023_auto_20191117_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteams',
            name='invitation_token',
            field=models.CharField(default='luster-unleaded-chill-polar', max_length=100),
        ),
    ]
