# Generated by Django 2.2.7 on 2019-11-15 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import regsys_api.uploader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamUploadFile',
            fields=[
                ('file', models.FileField(upload_to=regsys_api.uploader.models.generate_upload_path)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=200)),
                ('file_size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('team_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_owner', to='hackathon.HackathonTeams')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalUploadFile',
            fields=[
                ('file', models.FileField(upload_to=regsys_api.uploader.models.generate_upload_path)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=200)),
                ('file_size', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
